// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

import { referenceRedirects } from './content-manifest.mjs';

// The release version is resolved by scripts/sync-content.mjs (prebuild) and
// written to src/version.json; the SiteTitle and Footer components read it, so
// the config itself no longer needs to shell out to git.

// https://astro.build/config
export default defineConfig({
  site: 'https://mat-docs.shukelabs.com',
  // Every former top-level route (/overview/, /faq/, /quickstart-*/, ...) keeps
  // working by redirecting to its new /reference/<slug>/ home. The map is
  // derived from approvedPageSlugs(), so a new page's redirect cannot be
  // forgotten here.
  redirects: referenceRedirects(),
  integrations: [
    starlight({
      title: 'my-ai-team',
      description:
        'Public documentation for my-ai-team — a tmux-based framework for running structured AI-agent sessions against a GitHub repo. Latest release only.',
      // Starlight ships Pagefind site search by default (no extra config).
      // SiteTitle override adds the version badge + CC-BY link into the site
      // header (inherited by every route); Footer repeats the licence notice.
      // Header override adds the Buy Now purchase CTA to the same header.
      components: {
        Header: './src/components/Header.astro',
        SiteTitle: './src/components/SiteTitle.astro',
        Footer: './src/components/Footer.astro',
      },
      // The evaluator pages are hand-authored and fixed in the Understand
      // group; the Reference group is autogenerated from the generated
      // reference/ section: the pages carry `sidebar.order` frontmatter emitted
      // by scripts/sync-content.mjs, so adding a page to docs/public/ changes
      // the sidebar with no edit here.
      sidebar: [
        {
          label: 'Understand',
          items: [
            { label: 'How it works', slug: 'how-it-works' },
            { label: 'Modes', slug: 'modes' },
            { label: 'Compare', slug: 'compare' },
          ],
        },
        { label: 'Reference', items: [{ autogenerate: { directory: 'reference' } }] },
      ],
    }),
  ],
});
